package cmd

import (
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/egorbanin/speka/speka"
	"github.com/egorbanin/speka/speka/generator"

	"github.com/hjson/hjson-go/v4"
	"github.com/spf13/cobra"
)

func init() {
	rootCmd.AddCommand(goStructs)
	goStructs.Flags().String("package", "", "package")
}

var goStructs = &cobra.Command{
	Use: "go.structs",
	RunE: func(cmd *cobra.Command, args []string) error {
		pckg, err := cmd.Flags().GetString("package")
		if err != nil {
			return fmt.Errorf("cmd.Flags().GetString: %w", err)
		}

		var b []byte
		if path != "" {
			b, err = os.ReadFile(path)
			if err != nil {
				return fmt.Errorf("os.ReadFile %s: %w", path, err)
			}
		} else {
			b, err = io.ReadAll(os.Stdin)
			if err != nil {
				return fmt.Errorf("io.ReadAll %s: %w", path, err)
			}
		}

		var s speka.Speka
		if err := hjson.Unmarshal(b, &s); err != nil {
			return fmt.Errorf("hjson.Unmarshal: %w", err)
		}

		p := s.Name
		if pckg != "" {
			p = pckg
		}

		genComment := fmt.Sprintf("Code generated by `%s`. DO NOT EDIT.", strings.Join(os.Args, " "))
		gen := generator.NewGoFile("", genComment, p)
		for name, m := range s.Methods {
			p, err := speka.ParseProperty(fmt.Sprintf("%s_rq", name), m.Rq)
			if err != nil {
				return fmt.Errorf("speka.ParseProperty: %w", err)
			}

			if err := gen.AddProperty(p, generator.GoStructOpts{
				Validator: true,
			}); err != nil {
				return fmt.Errorf("gen.AddProperty: %w", err)
			}

			p, err = speka.ParseProperty(fmt.Sprintf("%s_rs", name), m.Rs)
			if err != nil {
				return fmt.Errorf("speka.ParseProperty: %w", err)
			}

			if err := gen.AddProperty(p, generator.GoStructOpts{}); err != nil {
				return fmt.Errorf("gen.AddProperty: %w", err)
			}
		}

		gen.Write(os.Stdout)

		return nil
	},
}
